Model mean sea level - nowcasts

* What is the mean sea level of the model?
* Is it close to 0? 
* Trying to determine if z=0 in the model corresponds to mean sea level.

In [1]:
import numpy as np
import netCDF4 as nc

from salishsea_tools import tidetools, places, geo_tools
from nowcast import analyze
from nowcast.figures import figures
import datetime

In [2]:
b = '/data/nsoontie/MEOPAR/NEMO-forcing/grid/bathy_meter_SalishSea2.nc'

grid_B = nc.Dataset(b)
X=grid_B.variables['nav_lon'][:]
Y=grid_B.variables['nav_lat'][:]
bathy =grid_B.variables['Bathymetry'][:]

to=datetime.datetime(2015,8,1)
tf=datetime.datetime(2016,7,31)
files = analyze.get_filenames(to,tf,'1d','grid_T','/results/SalishSea/nowcast/')

Look up mean sea level at a few points in the model.

In [3]:
names = ['Point Atkinson','Campbell River',  'Victoria', 'Neah Bay', 'Cherry Point', 'Friday Harbor',
        'Sandheads']

print('Date range: {} to {} '.format(to.strftime('%d-%b-%Y'), tf.strftime('%d-%b-%Y')))
for name in names:
    lat = figures.SITES[name]['lat']
    lon = figures.SITES[name]['lon']

    j, i = geo_tools.find_closest_model_point(lon,lat,X,Y,land_mask=bathy.mask) 

    ssh, time =analyze.combine_files(files,'sossheig','None',j,i)
    
    print('{} mean ssh: {}'.format(name, np.mean(ssh)))

Date range: 01-Aug-2015 to 31-Jul-2016
Point Atkinson mean ssh: 0.1483176052570343
Campbell River mean ssh: 0.028050417080521584
Victoria mean ssh: 0.03751243278384209
Neah Bay mean ssh: -0.008689958602190018
Cherry Point mean ssh: 0.09488401561975479
Friday Harbor mean ssh: 0.04296523705124855
Sandheads mean ssh: 0.128698468208313

Do these values reflect anamolies unqiue to this time period? Probably not, because I would expect them to be closer together.

How do the actual water levels compare with a long term mean sea level?

In [4]:
DFO = ['Point Atkinson', 'Campbell River', 'Victoria']

print('Date range: {}  to {} '.format(to.strftime('%d-%b-%Y'), tf.strftime('%d-%b-%Y')))

for name in DFO:
    obs = figures.load_archived_observations(name,to.strftime('%d-%b-%Y'), tf.strftime('%d-%b-%Y'))
    print('{} mean sea level - long term mean: {}'.format(name, np.mean(obs.wlev) - figures.SITES[name]['msl']))

NOAA = ['Neah Bay', 'Cherry Point', 'Friday Harbor']    
for name in NOAA:
    obs = figures.get_NOAA_wlevels(figures.SITES[name]['stn_no'],to.strftime('%d-%b-%Y'), tf.strftime('%d-%b-%Y'),
                                  product='hourly_height')
    print('{} mean sea level of observations {}'.format(name, np.mean(obs.wlev) ))

Date range: 01-Aug-2015  to 31-Jul-2016
Point Atkinson mean sea level - long term mean: 0.11366033611148874
Campbell River mean sea level - long term mean: -0.0009480874316922794
Victoria mean sea level - long term mean: 0.1307841530054643
Neah Bay mean sea level of observations 0.02554850746268665
Cherry Point mean sea level of observations 0.06906766169154191
Friday Harbor mean sea level of observations 0.10489042288557159

* I think I will have to keep an eye on this. The longer time series I have, the less I should have to compare with a long term msl in the observations.
* spinups are useless because we used the atmospheric pressure incorrectly.

In [5]:
obs

                          time   wlev   Sigma   I   L
0    2015-08-01 00:00:00+00:00  0.486   0.009   0    0
1    2015-08-01 01:00:00+00:00  0.805   0.018   0    0
2    2015-08-01 02:00:00+00:00  0.941   0.002   0    0
3    2015-08-01 03:00:00+00:00  0.944   0.005   0    0
4    2015-08-01 04:00:00+00:00  0.759   0.004   0    0
5    2015-08-01 05:00:00+00:00  0.530   0.005   0    0
6    2015-08-01 06:00:00+00:00  0.366   0.003   0    0
7    2015-08-01 07:00:00+00:00  0.314   0.002   0    0
8    2015-08-01 08:00:00+00:00  0.380   0.002   0    0
9    2015-08-01 09:00:00+00:00  0.538   0.002   0    0
10   2015-08-01 10:00:00+00:00  0.754   0.003   0    0
11   2015-08-01 11:00:00+00:00  0.897   0.001   0    0
12   2015-08-01 12:00:00+00:00  0.931   0.002   0    0
13   2015-08-01 13:00:00+00:00  0.780   0.003   0    0
14   2015-08-01 14:00:00+00:00  0.469   0.005   0    0
15   2015-08-01 15:00:00+00:00  0.020   0.010   0    0
16   2015-08-01 16:00:00+00:00 -0.609   0.013   0    0
17   2015-08-01 17:00:00+00:00 -1.235   0.010   0    0
18   2015-08-01 18:00:00+00:00 -1.648   0.009   0    0
19   2015-08-01 19:00:00+00:00 -1.763   0.004   0    0
20   2015-08-01 20:00:00+00:00 -1.570   0.017   0    0
21   2015-08-01 21:00:00+00:00 -1.253   0.012   0    0
22   2015-08-01 22:00:00+00:00 -0.769   0.007   0    0
23   2015-08-01 23:00:00+00:00 -0.184   0.009   0    0
24   2015-08-02 00:00:00+00:00  0.331   0.012   0    0
25   2015-08-02 01:00:00+00:00  0.730   0.017   0    0
26   2015-08-02 02:00:00+00:00  0.993   0.004   0    0
27   2015-08-02 03:00:00+00:00  1.047   0.004   0    0
28   2015-08-02 04:00:00+00:00  0.924   0.011   0    0
29   2015-08-02 05:00:00+00:00  0.670   0.006   0    0
...                        ...    ...     ...  ..  ...
8010 2016-06-29 18:00:00+00:00 -0.426   0.004   0    0
8011 2016-06-29 19:00:00+00:00 -0.171   0.006   0    0
8012 2016-06-29 20:00:00+00:00  0.010   0.012   0    0
8013 2016-06-29 21:00:00+00:00  0.103   0.007   0    0
8014 2016-06-29 22:00:00+00:00  0.117   0.004   0    0
8015 2016-06-29 23:00:00+00:00  0.066   0.018   0    0
8016 2016-06-30 00:00:00+00:00 -0.026   0.005   0    0
8017 2016-06-30 01:00:00+00:00 -0.112   0.010   0    0
8018 2016-06-30 02:00:00+00:00 -0.072   0.004   0    0
8019 2016-06-30 03:00:00+00:00  0.095   0.005   0    0
8020 2016-06-30 04:00:00+00:00  0.320   0.004   0    0
8021 2016-06-30 05:00:00+00:00  0.583   0.005   0    0
8022 2016-06-30 06:00:00+00:00  0.822   0.003   0    0
8023 2016-06-30 07:00:00+00:00  1.008   0.001   0    0
8024 2016-06-30 08:00:00+00:00  1.034   0.001   0    0
8025 2016-06-30 09:00:00+00:00  0.900   0.004   0    0
8026 2016-06-30 10:00:00+00:00  0.616   0.006   0    0
8027 2016-06-30 11:00:00+00:00  0.170   0.007   0    0
8028 2016-06-30 12:00:00+00:00 -0.373   0.010   0    0
8029 2016-06-30 13:00:00+00:00 -0.888   0.006   0    0
8030 2016-06-30 14:00:00+00:00 -1.277   0.004   0    0
8031 2016-06-30 15:00:00+00:00 -1.445   0.011   0    0
8032 2016-06-30 16:00:00+00:00 -1.391   0.005   0    0
8033 2016-06-30 17:00:00+00:00 -1.189   0.008   0    0
8034 2016-06-30 18:00:00+00:00 -0.876   0.005   0    0
8035 2016-06-30 19:00:00+00:00 -0.530   0.006   0    0
8036 2016-06-30 20:00:00+00:00 -0.198   0.005   0    0
8037 2016-06-30 21:00:00+00:00  0.092   0.007   0    0
8038 2016-06-30 22:00:00+00:00  0.256   0.009   0    0
8039 2016-06-30 23:00:00+00:00  0.337   0.017   0    0

[8040 rows x 5 columns]